-- Application bindings
-- These keys are already bound by Omarchy defaults; unbind before rebinding
-- so the dispatcher does not fire twice.
hl.unbind("SUPER + ALT + RETURN")
o.bind("SUPER + ALT + RETURN", "Tmux", "uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\" tmux new")
hl.unbind("SUPER + RETURN")
o.bind("SUPER + RETURN", "Terminal", "uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\"")
hl.unbind("SUPER + SHIFT + RETURN")
o.bind("SUPER + SHIFT + RETURN", "Browser", "omarchy-launch-browser")
hl.unbind("SUPER + SHIFT + F")
o.bind("SUPER + SHIFT + F", "File manager", "uwsm-app -- nautilus --new-window")
hl.unbind("SUPER + ALT + SHIFT + F")
o.bind("SUPER + ALT + SHIFT + F", "File manager (cwd)", "uwsm-app -- nautilus --new-window \"$(omarchy-cmd-terminal-cwd)\"")
hl.unbind("SUPER + SHIFT + B")
o.bind("SUPER + SHIFT + B", "Browser", "omarchy-launch-browser")
hl.unbind("SUPER + SHIFT + ALT + B")
o.bind("SUPER + SHIFT + ALT + B", "Browser (private)", "omarchy-launch-browser --private")
hl.unbind("SUPER + SHIFT + M")
o.bind("SUPER + SHIFT + M", "Music", "omarchy-launch-or-focus spotify")
hl.unbind("SUPER + SHIFT + ALT + M")
o.bind("SUPER + SHIFT + ALT + M", "Music TUI", "omarchy-launch-or-focus-tui cliamp")
hl.unbind("SUPER + SHIFT + N")
o.bind("SUPER + SHIFT + N", "Editor", "omarchy-launch-editor")
hl.unbind("SUPER + SHIFT + D")
o.bind("SUPER + SHIFT + D", "Docker", "omarchy-launch-tui lazydocker")
hl.unbind("SUPER + SHIFT + G")
o.bind("SUPER + SHIFT + G", "Signal", "omarchy-launch-or-focus ^signal$ \"uwsm-app -- signal-desktop\"")
hl.unbind("SUPER + SHIFT + O")
o.bind("SUPER + SHIFT + O", "Obsidian", "omarchy-launch-or-focus ^obsidian$ \"uwsm-app -- obsidian\"")
hl.unbind("SUPER + SHIFT + W")
o.bind("SUPER + SHIFT + W", "Typora", "uwsm-app -- typora --enable-wayland-ime")
hl.unbind("SUPER + SHIFT + SLASH")
o.bind("SUPER + SHIFT + SLASH", "Passwords", "uwsm-app -- 1password")

-- Web app bindings
hl.unbind("SUPER + SHIFT + A")
o.bind("SUPER + SHIFT + A", "ChatGPT", "omarchy-launch-webapp \"https://chatgpt.com\"")
hl.unbind("SUPER + SHIFT + ALT + A")
o.bind("SUPER + SHIFT + ALT + A", "Grok", "omarchy-launch-webapp \"https://grok.com\"")
hl.unbind("SUPER + SHIFT + C")
o.bind("SUPER + SHIFT + C", "Calendar", "omarchy-launch-webapp \"https://app.hey.com/calendar/weeks/\"")
hl.unbind("SUPER + SHIFT + E")
o.bind("SUPER + SHIFT + E", "Email", "omarchy-launch-webapp \"https://app.hey.com\"")
hl.unbind("SUPER + SHIFT + Y")
o.bind("SUPER + SHIFT + Y", "YouTube", "omarchy-launch-webapp \"https://youtube.com/\"")
hl.unbind("SUPER + SHIFT + ALT + G")
o.bind("SUPER + SHIFT + ALT + G", "WhatsApp", "omarchy-launch-or-focus-webapp WhatsApp \"https://web.whatsapp.com/\"")
hl.unbind("SUPER + SHIFT + CTRL + G")
o.bind("SUPER + SHIFT + CTRL + G", "Google Messages", "omarchy-launch-or-focus-webapp \"Google Messages\" \"https://messages.google.com/web/conversations\"")
hl.unbind("SUPER + SHIFT + P")
o.bind("SUPER + SHIFT + P", "Google Photos", "omarchy-launch-or-focus-webapp \"Google Photos\" \"https://photos.google.com/\"")
hl.unbind("SUPER + SHIFT + X")
o.bind("SUPER + SHIFT + X", "X", "omarchy-launch-webapp \"https://x.com/\"")
hl.unbind("SUPER + SHIFT + ALT + X")
o.bind("SUPER + SHIFT + ALT + X", "X Post", "omarchy-launch-webapp \"https://x.com/compose/post\"")

-- Hardware, layout, and window manager overrides
o.bind("F13", nil, "asusctl led-mode next")

hl.unbind("SUPER + W")
o.bind("SUPER + E", nil, "nautilus")
o.bind("SUPER + D", "Toggle floating", hl.dsp.window.float({ action = "toggle" }))
o.bind("SUPER + Q", nil, hl.dsp.window.close())
o.bind("SUPER + W", "Browser", "omarchy-launch-browser")
o.bind("SUPER + ALT + W", "Next wallpaper", "omarchy-theme-bg-next")

o.bind("SUPER + F9", "Gamma boost (night vision)", "busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Gamma d 0.4")
o.bind("SUPER + F10", "Gamma reset", "busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Gamma d 1.0")

hl.unbind("SUPER + CTRL + LEFT")
hl.unbind("SUPER + CTRL + RIGHT")
o.bind("SUPER + CTRL + RIGHT", "Move window to next workspace", hl.dsp.window.move({ workspace = "+1" }))
o.bind("SUPER + CTRL + LEFT", "Move window to previous workspace", hl.dsp.window.move({ workspace = "-1" }))

-- Speech-to-text
o.bind("SUPER + ALT + D", "Speech-to-text", "/usr/lib/hyprwhspr/config/hyprland/hyprwhspr-tray.sh record")

-- Searchable clipboard history
o.bind("ALT + V", "Paste history", "omarchy-shell shell toggle omarchy.clipboard")
