# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 2
    gaps_out = 2.4
    border_size = 2

    # Drag window borders to resize
    resize_on_border = true
    extend_border_grab_area = 15

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# Smart gaps: no gaps/border when only one tiled window
# Prevent new windows from automatically joining groups
group {
    auto_group = false
}

# Pressing the same workspace key toggles back to previous workspace
binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
}
